name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: ls -la
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adobuildagent:$(date +%s)
