name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.digitalocean.com/cr-gwit01/adobuildagent:$GITHUB_SHA_SHORT
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.CONTAINER_REGISTRY_SECRET }}
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/cr-gwit01/adobuildagent:$GITHUB_SHA_SHORT
